# Generated by Django 3.1.4 on 2020-12-07 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=15, max_digits=20)),
                ('customer_visits', models.IntegerField()),
                ('food_specialty', models.CharField(max_length=200)),
                ('patrons', models.CharField(blank=True, max_length=200)),
                ('revenue', models.CharField(blank=True, max_length=200)),
                ('restaurant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restauranttype')),
            ],
        ),
    ]
